# Quarkus Configuration
quarkus.application.name=s3-demo

# S3 JWKS Polling Configuration
auth.s3.bucket=auth-bucket
auth.s3.key=jwks.json
auth.s3.endpoint=http://localhost:4566
auth.s3.region=us-east-1

# S3 Polling Scheduler Configuration (Interval and Initial Delay)
auth.polling.every=10s
auth.polling.delay=10s

# LocalStack default test credentials
auth.s3.access-key=test
auth.s3.secret-key=test

# Server Required Scope Policy
auth.required-scope=read

# Private Key Path (Mounted secret volume in production / container, fallback to classpath resource)
auth.jwt.private-key-path=${AUTH_PRIVATE_KEY_PATH:/etc/auth/private_key.pem}
